import React, { Component, PropTypes } from 'react';
import { Row, Col, Table } from 'antd';
import { Link } from 'react-router';
import MainLayout from '../components/layouts/SimpleLayout/SampleMainLayout.jsx';

const pagination = {
  total: 100,
  current:1,
  defaultCurrent:1,
  pageSize:100,
  showSizeChanger: true,
  onShowSizeChange(current, pageSize) {
    console.log('Current: ', current, '; PageSize: ', pageSize);
  },
  onChange(current) {
    console.log('Current: ', current);
  }
};

const columns = [{
  title: '栏目名称',
  dataIndex: 'name',
}, {
  title: '链接地址',
  dataIndex: 'url',
  render: (text, record) => <a href={'#'+text}>{text}</a>
}];

const data=[
    {
        name:"首页",
        url:"/index"
    },
    {
        name:"测试-Component"
    },
    {
        name:"测试-Component-BodyGridTable",
        url:"/test/BodyGridTable"
    },
    {
      name:"测试"
    },
    {
        name:"测试-Org",
        url:"/test/Org"
    },
    {
        name:"测试-AddApprovalCertModal",
        url:"/test/AddApprovalCertModal"
    },
    {
      name:"测试-AssOrg",
      url:"/test/AssOrg"
    },
    {
      name:"测试-AddAssOrg",
      url:"/test/AddAssOrg"
    },
    {
        name:"测试-OrgDetailModal",
        url:"/test/OrgDetailModal"
    },
    {
        name:"测试-EditOrgInfoPage",
        url:"/test/EditOrgInfoPage"
    },
    {
        name:"测试-OrgBasicInfoForm",
        url:"/test/OrgBasicInfoForm"
    },
    {
        name:"测试-CiqCodeModal",
        url:"/test/CiqCodeModal"
    },
    {
        name:"测试-ProductDetailModal",
        url:"/test/ProductDetailModal"
    },
    {
        name:"测试-ProductSelectPage",
        url:"/test/ProductSelectPage"
    },
    {
        name:"测试-SetProductAccountModal",
        url:"/test/SetProductAccountModal"
    },
    {
        name:"测试-Product",
        url:"/test/Product"
    },
    {
        name:"测试-AddProductModal",
        url:"/test/AddProductModal"
    },
    {
        name:"测试-ApprovalCertificate",
        url:"/test/ApprovalCertificate"
    },
    {
        name:"测试-AddApprovalCertModal",
        url:"/test/AddApprovalCertModal"
    },
    {
        name:"测试-ApprovalProductSelectModal",
        url:"/test/ApprovalProductSelectModal"
    },
    {
        name:"测试-UploadCertificateModal",
        url:"/test/UploadCertificateModal"
    },
    {
        name:"测试-VerificationCert",
        url:"/test/VerificationCert"
    },
    {
        name:"测试-FillVerificationCertPage",
        url:"/test/FillVerificationCertPage"
    },
    {
        name:"测试-AddVerificationCertModal",
        url:"/test/AddVerificationCertModal"
    },
    {
        name:"测试-RemainedSubmitApproval",
        url:"/test/RemainedSubmitApproval"
    },
    {
        name:"测试-AddPreApprovalT3Modal",
        url:"/test/AddPreApprovalT3Modal"
    },
    {
        name:"测试-ViewPreApprovalT3Modal",
        url:"/test/ViewPreApprovalT3Modal"
    },
    {
        name:"测试-DispatchPreApprovalModal",
        url:"/test/DispatchPreApprovalModal"
    },
    {
        name:"测试-RemainedAuditApproval",
        url:"/test/RemainedAuditApproval"
    },
    {
        name:"测试-ReportQuery",
        url:"/test/ReportQuery"
    },
    {
        name:"测试-CompletedApproval",
        url:"/test/CompletedApproval"
    },
    {
        name:"测试-SiteUnAssessC",
        url:"/test/SiteUnAssessC"
    },
    {
        name:"测试-SiteInAssessC",
        url:"/test/SiteInAssessC"
    },
    {
        name:"测试-SiteCompletedAssessC",
        url:"/test/SiteCompletedAssessC"
    },
    {
        name:"测试-Order",
        url:"/test/Order"
    },
    {
        name:"测试-AddCheckOrderModal",
        url:"/test/AddCheckOrderModal"
    },
    {
        name:"测试-AddOrderCargoModal",
        url:"/test/AddOrderCargoModal"
    },
    {
        name:"测试-DisplayOrderStatusModal",
        url:"/test/DisplayOrderStatusModal"
    },
    {
        name:"测试-ViewCheckOrderModal",
        url:"/test/ViewCheckOrderModal"
    },
    {
        name:"测试-ViewCheckOrderModalForY",
        url:"/test/ViewCheckOrderModalForY"
    },
    {
        name:"测试-TMSOrder",
        url:"/test/TMSOrder"
    },
    {
        name:"测试-AddTMSOrderModal",
        url:"/test/AddTMSOrderModal"
    },
    {
        name:"测试-ViewTMSOrderModal",
        url:"/test/ViewTMSOrderModal"
    },
    {
        name:"测试-AddOrderCargoModal",
        url:"/test/AddOrderCargoModal"
    },
    {
        name:"测试-AddTMSOrderProductModal",
        url:"/test/AddTMSOrderProductModal"
    },
    {
        name:"测试-TMSOrderDetailModal",
        url:"/test/TMSOrderDetailModal"
    },
    {
        name:"测试-DispatchTMSOrderModal",
        url:"/test/DispatchTMSOrderModal"
    },
    {
        name:"测试-SelectOrderModal",
        url:"/test/SelectOrderModal"
    },
    {
        name:"测试-ReceiptAndSend",
        url:"/test/ReceiptAndSend"
    },
    {
        name:"测试-AddReceiptAndSendModal",
        url:"/test/AddReceiptAndSendModal"
    },
    {
        name:"测试-Send",
        url:"/test/Send"
    },
    {
        name:"测试-AddSendModal",
        url:"/test/AddSendModal"
    },
    {
        name:"测试-CheckNotification",
        url:"/test/CheckNotification"
    },
    {
        name:"测试-AddCheckNotificationModal",
        url:"/test/AddCheckNotificationModal"
    },
    {
        name:"测试-AddCheckNotificationCargoModal",
        url:"/test/AddCheckNotificationCargoModal"
    },
    {
        name:"测试-ViewCheckNotification",
        url:"/test/ViewCheckNotification"
    },
    {
        name:"测试-DispatchCheckTaskModal",
        url:"/test/DispatchCheckTaskModal"
    },
    {
        name:"测试-AddCheckTaskModal",
        url:"/test/AddCheckTaskModal"
    },
    {
        name:"测试-AddCheckPersonModal",
        url:"/test/AddCheckPersonModal"
    },
    {
        name:"测试-CheckTask",
        url:"/test/CheckTask"
    },
    {
        name:"测试-ViewCheckTask",
        url:"/test/ViewCheckTask"
    },
    {
        name:"测试-ViewCheckTaskForECIQModal",
        url:"/test/ViewCheckTaskForECIQModal"
    },
    {
        name:"测试-WriteCheckResultModal",
        url:"/test/WriteCheckResultModal"
    },
    {
        name:"测试-WriteCheckResultNotPassModal",
        url:"/test/WriteCheckResultNotPassModal"
    },
    {
        name:"测试-AddCheckTaskCargoModal",
        url:"/test/AddCheckTaskCargoModal"
    },
    {
        name:"测试-CheckResult",
        url:"/test/CheckResult"
    },
    {
        name:"测试-ViewCheckResultModal",
        url:"/test/ViewCheckResultModal"
    },
    {
        name:"测试-ViewCheckResultForECIQModal",
        url:"/test/ViewCheckResultForECIQModal"
    },
    {
        name:"测试-ProcessedCheckTask",
        url:"/test/ProcessedCheckTask"
    },
    {
        name:"测试-后续监管",
        url:""
    },
    {
        name:"测试-Use",
        url:"/test/Use"
    },
    {
        name:"测试-FollowUpSupervisionList",
        url:"/test/FollowUpSupervisionList"
    },
    {
        name:"测试-医智捷",
        url:""
    },
    {
        name:"测试-YZJOrder",
        url:"/test/YZJOrder"
    },
    {
        name:"测试-YZJTMSOrder",
        url:"/test/YZJTMSOrder"
    },
    {
        name:"测试-YZJCheckNotification",
        url:"/test/YZJCheckNotification"
    },
    {
        name:"测试-YZJCheckTask",
        url:"/test/YZJCheckTask"
    },
    {
        name:"测试-用户",
        url:""
    },
    {
        name:"测试-COrder",
        url:"/test/COrder"
    },
    {
        name:"测试-CTMSOrder",
        url:"/test/CTMSOrder"
    },
    {
        name:"测试-CCheckResult",
        url:"/test/CCheckResult"
    },
    {
        name:"测试-商检",
        url:""
    },
    {
        name:"测试-ECheckNotification",
        url:"/test/ECheckNotification"
    },
    {
        name:"测试-ECheckTask",
        url:"/test/ECheckTask"
    },
    {
        name:"测试-用户",
        url:""
    },
    {
        name:"测试-Audit",
        url:"/test/Audit"
    },
    {
        name:"测试-Management",
        url:"/test/Management"
    },
    {
        name:"测试-平台",
        url:""
    },
    {
        name:"测试-Register",
        url:"/test/Register"
    },
    /*{
        name:"测试-商检-查验员",
        url:""
    },
    {
        name:"测试-ECVUnConfirmedCheckTask",
        url:"/test/ECVUnConfirmedCheckTask"
    },
    {
        name:"测试-ECVConfirmedCheckTask",
        url:"/test/ECVConfirmedCheckTask"
    },*/
]

const App = ({ location }) => {
  return (
    <MainLayout>
      <Row type="flex" justify="center">
        <Col span={22}>
          <Table columns={columns} dataSource={data} size="small" pagination={pagination} rowKey={(record,i)=>{return "key"+i}}/>
        </Col>
      </Row>
    </MainLayout>
  );
};

App.propTypes = {
};

export default App;
